version: "3.9"

services:
  db:
    image: "mysql:8.0.16"
    container_name: "db"
    ports:
      - "3333:3306"
    restart: always
    environment:
      - MYSQL_PASSWORD=123
      - MYSQL_USER=root
      - MYSQL_DB= docker_test